### ISSUE TITLE
feat: "Is update available?"

### ISSUE THREAD

**Issue by Korpip** [revanced/revanced-cli#120]
### Type

Cosmetic

### Issue

Checking for updates for application/patches is not centralized.

### Feature

Check for latest build numbers on landing page beside application names VS last built version.

### Motivation

Unless there is another easier way that is not described in the readme it is a lot of manual checking for each application.  Checking for each application one at a time does not scale well as more applications are added.
With one page showing latest builds even non rooted users can quickly go back and forth between application information screen and the landing page.

**Comment by Shadow-Hunt3r** [comment]
it could be a good idea since it might be possible to prompt the user to download and then run a set of commands(depending on OS version) that can run compatibly and download, package with same included or excluded patches as the version previous which could be read from a log or presets that a user applied on their own end

**Comment by oSumAtrIX** [comment]
This is out of the scope for ReVanced CLI as it is meant to work completely offline.
