### ISSUE TITLE
feat: throw if user includes non-existent patch

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-cli#244]
### Type

Functionality

### Issue

Currently, CLI sliently ignores non-existent patch if you include it. This sometimes makes it frustrating to debug why a patch isn't being included just because you made typo. This also goes against UX because the user should receive feedback if they do action.

### Feature

Simple solution. Throw if the user includes a non-existent patch. This would fix all the issues mentioned above without any drawbacks, because if you did something wrong, you should get an error (aka. feedback).

Unix commands also follow this style of "throw error immediately if something goes wrong". For example, the `rm` command:
```sh
$ touch file
$ rm -f file nonexistentfile
rm: cannot remove 'nonexistentfile': No such file or directory
```

### Motivation

It makes for better UX.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
> without any drawbacks, because if you did something wrong, you should get an error (aka. feedback)

The drawback is that ReVanced CLI is now fragile to user input. Currently, it silently ignores any incorrect input allowing you to remove and add bundles without worrying about your selection. If it were to throw and cancel the execution, the input must also be considered. 

> This sometimes makes it frustrating to debug why a patch isn't being included just because you made typo

Explain how it makes it frustrating to debug. Any patch you include and is included is confirmed by a log.

> This also goes against UX because the user should receive feedback if they do action.

Feedback is provided via the log, as mentioned above.

> Unix commands also follow this style of "throw error immediately if something goes wrong". For example, the rm command:

`rm` is designated to return an exception because that is all it is about, whereas ReVanced CLI takes in a batch of patch selections and then filters the patches from supplied bundles according to the filter.

An exception will not be raised for that reason because it would be frustrating having to adjust your patch selection every time you add or remove bundles, and at max, a warning should be issued.

**Comment by oSumAtrIX** [comment]
A warning should suffice. A flag to handle invalid input as severe can be added, but it would add unnecessary complexity.

**Comment by PalmDevs** [comment]
> The drawback is that ReVanced CLI is now fragile to user input. Currently, it silently ignores any incorrect input allowing you to remove and add bundles without worrying about your selection. If it were to throw and cancel the execution, the input must also be considered.  

Alright.

> Explain how it makes it frustrating to debug. Any patch you include and is included is confirmed by a log.
> Feedback is provided via the log, as mentioned above.

The log currently does not mention the non-existent patch and it also says nothing about the invalid user input, which makes it look like nothing about the non-existent patch was inputted at all which in turn makes it harder to debug.

> `rm` is designated to return an exception because that is all it is about, whereas ReVanced CLI takes in a batch of patch selections and then filters the patches from supplied bundles according to the filter.

And when entries do not exist, it should throw an error, no?  

**Hypothetical scenario**:  
Your friend needs some help getting things out of his fridge because he wants to make a meal. He asks you to take items and place them on the countertop. One of the items he's requesting **isn't** in the fridge. Instead of just **only** taking the items in the fridge and putting them on the countertop, you **should also mention** to your friend that some items are missing.

This exact same hypothetical scenario applies to the CLI. You are the CLI and your friend is the user using the CLI. Your friend's purpose isn't just only requesting the items for no reason, he wants to make a meal *(like how CLI takes patch names to filter them accordingly)*.

> An exception will not be raised for that reason because it would be frustrating having to adjust your patch selection every time you add or remove bundles, and at max, a warning should be issued.  

I half-agree with this, but you mentioned below that a flag could be added. So I think that's my final take on this.

**Comment by oSumAtrIX** [comment]
> The log currently does not mention the non-existent patch and it also says nothing about the invalid user input, which makes it look like nothing about the non-existent patch was inputted at all which in turn makes it harder to debug.

If you provided an invalid input and ReVanced CLI does not log it, this implies that your input is invalid.

> And when entries do not exist, it should throw an error, no?

If you want to include a patch that does not exist, execution can still proceed and should not raise an exception. Otherwise, the drawback mentioned in my previous comment applies. 

> This exact same hypothetical scenario applies to the CLI.

If I do not include a patch bundle but include its patches, an exception would force me to remove the patch selection too. The patch selection acts as a filter. If the patch you inputted does not exist, nothing from the patch bundle will be filtered away.

**Comment by PalmDevs** [comment]
> If you provided an invalid input and ReVanced CLI does not log it, this implies that your input is invalid.

Which means no feedback, therefore a warning (and or a flag for strict inputs) should exist.

> If you want to include a patch that does not exist, execution can still proceed and should not raise an exception. Otherwise, the drawback mentioned in my previous comment applies. 

Your proposed solution should work fine, a warning by default (and maybe a `--strict` *(for example)* flag to throw on invalid inputs).

**Comment by oSumAtrIX** [comment]
> Which means no feedback

It missing is a form of feedback. It means your input was incorrect. A warning is fine as explained above, not an error as you have proposed in #244.

**Comment by PalmDevs** [comment]
Sure, that works.
